import {
  BookOpen,
  Brain,
  Briefcase,
  Calendar,
  GraduationCap,
  Home,
  Search,
  Star,
  Target,
  User,
  Users,
  ClipboardList,
  Sparkles,
  LogOut,
  Moon,
  Sun,
  MapPin,
  School,
  ArrowLeft,
  ArrowRight,
  RefreshCw,
  AlertTriangle,
  Eye,
  EyeOff,
  Trophy,
  Clock3,
  Link2,
  Send,
  PartyPopper,
  Lightbulb,
} from 'lucide-react';

const icons = {
  home: Home,
  test: Brain,
  career: Target,
  courses: BookOpen,
  subjects: Briefcase,
  appointments: Calendar,
  ratings: Star,
  profile: User,
  teachers: Users,
  quiz: ClipboardList,
  ai: Sparkles,
  logout: LogOut,
  moon: Moon,
  sun: Sun,
  india: MapPin,
  school: School,
  graduate: GraduationCap,
  search: Search,
  back: ArrowLeft,
  next: ArrowRight,
  refresh: RefreshCw,
  warning: AlertTriangle,
  eye: Eye,
  eyeOff: EyeOff,
  trophy: Trophy,
  clock: Clock3,
  link: Link2,
  send: Send,
  success: PartyPopper,
  hint: Lightbulb,
};

export default function AppIcon({ name, size = 16, color = 'currentColor', strokeWidth = 2 }) {
  const Icon = icons[name];
  if (!Icon) return null;
  return <Icon size={size} color={color} strokeWidth={strokeWidth} />;
}
